name: Multi-CICD

on:
  push

env:
  VERSION: dev

jobs:
  Change-Detection:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      library: ${{ steps.filter.outputs.library }}
      consumer: ${{ steps.filter.outputs.consumer }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            library:
              - 'components/library/**'
            consumer:
              - 'components/consumer/**'


  Build-Test-Library:
    needs: Change-Detection
    if: ${{ needs.Change-Detection.outputs.library == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'cat'
        run: cat components/library/data.txt

  Build-Test-Consumer:
    needs: Change-Detection
    if: ${{ needs.Change-Detection.outputs.consumer == 'true' }} or ${{ needs.Change-Detection.outputs.library == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'cat'
        run: cat components/consumer/data.txt
    