name: A workflow for testing some Python
on: 
  push:
    paths:
      - 'new-action/**'

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./new-action
